name: Newman Tests

on: [push, pull_request]

jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Install Node.js
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # Install Newman and HTML Extra reporter
      - name: Install Newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      # Create directory for results
      - name: Make Directory for results
        run: mkdir -p testResults

      # Run Postman collection
      - name: Run API Tests
        run: |
          newman run "Restful Booker BVT.postman_collection.json" \
          -e Production.postman_environment.json \
          -r htmlextra \
          --reporter-htmlextra-export testResults/htmlreport.html || true

      # Upload test results
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: RunReports
          path: testResults
